
amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 8.0
    laser_min_range: 0.2
    laser_model_type: "likelihood_field"
    max_beams: 100
    max_particles: 2000
    min_particles: 100
    odom_frame_id: "odom"
    scan_topic: "/scan"
    tf_broadcast: true
    transform_tolerance: 1.0